### ISSUE TITLE
java string program

### ISSUE THREAD

**Issue by adarshrajsinha25** [adarshrajsinha25/JAVA#1]
you have to solve the java string program in best time complexity.

**Comment by Subhashini014** [comment]
could you please assign me this issue It would be very helpful to me to improve my skills.

**Comment by MeetD99** [comment]
Can you please assign it to me. I would like to work on this issue.

**Comment by MeetD99** [comment]
Hey @adarshrajsinha25 , I have successfully created a Pull Request. Please Verify it and Let me know of any Changes. Thank You! and Happy Coding!

**Comment by MeetD99** [comment]
Hi @adarshrajsinha25, Can you please add hacktoberfest-accepted label to my PR. It would help me get my Hacktoberfest Submission.
